version: "2.1"

services:
  master:
    image: kontena/server:${KONTENA_VERSION}
    environment:
      - RACK_ENV=production
      - MONGODB_URI=${KONTENA_MASTER_MONGODB_URI}
      - VAULT_KEY=${KONTENA_MASTER_VAULT_KEY}
      - VAULT_IV=${KONTENA_MASTER_VAULT_IV}
      - INITIAL_ADMIN_CODE=${KONTENA_MASTER_INITIAL_ADMIN_CODE}
      - ACME_ENDPOINT=https://acme-v01.api.letsencrypt.org/
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3.0
    restart: unless-stopped
    command: mongod --smallfiles
    volumes:
      - mongodb_master:/data/db

  haproxy:
    image: kontena/haproxy:latest
    restart: unless-stopped
    environment:
      - SSL_CERT=**None**
      - BACKENDS=kontena_master_1:9292
      - LE_DOMAINS=${KONTENA_MASTER_LE_CERT_HOSTNAME}
      - LE_EMAIL=${KONTENA_MASTER_LE_CERT_EMAIL}
    links:
      - master
    ports:
      - 80:80
      - 443:443

volumes:
  mongodb_master:
