version: "2.1"

services:
  agent:
    image: kontena/agent:${KONTENA_VERSION}
    container_name: kontena-agent
    environment:
      - KONTENA_URI=${KONTENA_MASTER_URI}
      - KONTENA_TOKEN=${KONTENA_GRID_TOKEN}
      - KONTENA_PEER_INTERFACE=${KONTENA_PEER_INTERFACE}
    network_mode: host
    restart: unless-stopped
# https://github.com/kontena/kontena/issues/1771, currently done in node/bin/initialize
#    labels:
#      - ${KONTENA_NODE_LABEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock