version: "2.1"

services:
  mongo-backup:
    image: mattipaksula/mongo-backup
    environment:
      - INTERVAL=${MONGO_BACKUP_INTERVAL}
      - MONGODB_HOST=${MONGO_BACKUP_MONGODB_HOST}
      - MONGODB_OPLOG=${MONGO_BACKUP_OPLOG}
      - MONGODB_LOCK=${MONGO_BACKUP_LOCK}
      - LOCAL_KEEP=${MONGO_BACKUP_LOCAL_KEEP}
      # slack
      - SLACK_WEBHOOK_URL=${MONGO_BACKUP_SLACK_WEBHOOK_URL}
      - SLACK_NOTIFY_ON_SUCCESS=${MONGO_BACKUP_SLACK_NOTIFY_ON_SUCCESS}
      - SLACK_NOTIFY_ON_WARNING=${MONGO_BACKUP_SLACK_NOTIFY_ON_WARNING}
      - SLACK_NOTIFY_ON_FAILURE=${MONGO_BACKUP_SLACK_NOTIFY_ON_FAILURE}
      - SLACK_USERNAME=${MONGO_BACKUP_SLACK_USERNAME}
    restart: unless-stopped
    volumes:
      - mongo_backup:/backup

volumes:
  mongo_backup:
