version: "2.1"

services:
  lb:
    image: kontena/haproxy:latest
    environment:
    restart: unless-stopped
    environment:
      - FRONTEND_PORT=80
      - BACKENDS=${LB_BACKENDS}
      - SSL_CERT=**None**
    ports:
      - 80:80
      - 443:443
